apiVersion: v2
name: prometheus-grafana
description: A Helm chart for deploying Prometheus and Grafana monitoring stack to Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - monitoring
  - prometheus
  - grafana
  - observability
home: https://github.com/your-org/prometheus-grafana
sources:
  - https://github.com/your-org/prometheus-grafana
maintainers:
  - name: Your Name
    email: your.email@company.com
annotations:
  category: Monitoring
dependencies:
  - name: prometheus
    version: "25.8.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: grafana
    version: "7.0.19"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
