{{- if and .Values.prometheus.enabled .Values.prometheus.alertmanager.enabled .Values.prometheus.alertmanager.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "prometheus-grafana.alertmanager.fullname" . }}
  labels:
    {{- include "prometheus-grafana.labels" . | nindent 4 }}
    {{- include "prometheus-grafana.monitoring.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
  {{- with .Values.prometheus.alertmanager.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.prometheus.alertmanager.ingress.className }}
  ingressClassName: {{ .Values.prometheus.alertmanager.ingress.className }}
  {{- end }}
  {{- if .Values.prometheus.alertmanager.ingress.tls }}
  tls:
    {{- range .Values.prometheus.alertmanager.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.prometheus.alertmanager.ingress.hosts }}
    - {{- if .host }}
      host: {{ .host | quote }}
      {{- end }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ include "prometheus-grafana.alertmanager.fullname" $ }}
                port:
                  number: {{ $.Values.prometheus.alertmanager.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
