name: Deploy to EKS with Helm

on:
  push:
    branches:
      - main

jobs:
  helm-deploy:
    runs-on: self-hosted
    name: Helm Upgrade to EKS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig from EKS
        run: |
          aws eks update-kubeconfig \
            --region "${{ secrets.AWS_REGION }}" \
            --name "${{ secrets.EKS_CLUSTER_NAME }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Verify kubeconfig / cluster access
        run: |
          kubectl get nodes
        env:
          KUBECONFIG: ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Upgrade Helm release
        run: |
          helm upgrade --install code-dev-app ./my-app \
            --namespace code-dev \
            --values ./my-app/values-dev.yaml \
            --create-namespace \
            --timeout 10m \
            --wait
        env:
          KUBECONFIG: ~/.kube/config
